dataset: cifar10
aa: null
batch_size: 128
color_jitter: 0.0
cutout_length: 16
decay_by_epoch: false
decay_epochs: 3
decay_rate: 0.967
drop: 0.0
epochs: 600
log_interval: 50
lr: 0.1
smoothing: 0.0
min_lr: 1.0e-06
model_ema: false
model_ema_decay: 0.9998
kd_loss_ema_decay: 0.99
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: cosine
seed: 42
warmup_epochs: 0
warmup_lr: 0.2
weight_decay: 1.0e-04
workers: 4
sgd_no_nesterov: True
opt_no_filter: True
clip_grad_max_norm: 1.0
# dyrep
dyrep: False
dyrep_adjust_interval: 15
dyrep_recal_bn_every_epoch: False
# kd
ori_loss_weight:  1.
kd_loss_weight: 1.
kd: learnable_kd
teacher_model: 'cifar_vgg16'
teacher_pretrained: True
teacher_ckpt: 'experiments/vgg16_cifar10_exp/best.pth.tar'
model_config: 'configs/models/VGG/vgg16_half_cifar10.yaml'
experiment: learnable_kd_loss_cifar10
kd_opt: sgd
kd_lr: 1e-3
kd_opt_eps: 1.0e-08
kd_momentum: 0.9
kd_weight_decay: 1e-4
update_student_params_steps: 50